### PR TITLE
Update requirements for packing

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
To address the issue in https://github.com/conda-forge/amset-feedstock/pull/22

**Comment by jan-janssen** [comment]
@albop We had an issue with `amset` which requires on `interpolation` that the `pip check` command causes an error because the restrictions for `interpolation` defined on pypi are not correctly represented in the `meta.yaml` file. I updated the `meta.yaml` file to fix this issue and then added the `pip check` to identify the issue more quickly in case it comes up again in the future. Can you take a look at this pull request, approve and merge it?

**Comment by albop** [comment]
Thank you @jan-janssen ! I'll merge this now.

**Pull request merged**
