### PR TITLE
Add grayskull updates

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by albop** [comment]
I'm unfamiliar with grayskull but will trust you on that one.

**Comment by albop** [comment]
Actually, this PR is still for interpolation=2.2.5. If you want to make another build for that version you need te decrease back the numba version. 
In short interpolation<=2.2.5 used @generated_jit from numba which is not available anymore in latest numba. That's why interpolation=2.2.6 switched to @overload

**Comment by jan-janssen** [comment]
> I'm unfamiliar with grayskull but will trust you on that one.

It is basically a tool to automatically update the conda-forge package including dependencies. It uses https://github.com/conda/grayskull in the background.

**Pull request merged**
