### PR TITLE
Enable Python 3.10

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by albop** [comment]
@conda-forge-admin, please re-render.

**Comment by jan-janssen** [comment]
@conda-forge-admin, please re-render.

**Comment by jan-janssen** [comment]
```
    Running command /home/conda/feedstock_root/build_artifacts/interpolation_1663770803280/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python /home/conda/feedstock_root/build_artifacts/interpolation_1663770803280/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpa7md9gzf
    Traceback (most recent call last):
      File "/home/conda/feedstock_root/build_artifacts/interpolation_1663770803280/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
        main()
      File "/home/conda/feedstock_root/build_artifacts/interpolation_1663770803280/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/conda/feedstock_root/build_artifacts/interpolation_1663770803280/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py", line 110, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/home/conda/feedstock_root/build_artifacts/interpolation_1663770803280/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
        poetry = Factory().create_poetry(Path(".").resolve(), with_dev=False)
      File "/home/conda/feedstock_root/build_artifacts/interpolation_1663770803280/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.10/site-packages/poetry/core/factory.py", line 43, in create_poetry
        raise RuntimeError("The Poetry configuration is invalid:\n" + message)
    RuntimeError: The Poetry configuration is invalid:
      - Additional properties are not allowed ('group' was unexpected)

    Preparing wheel metadata: finished with status 'error'
```

**Comment by albop** [comment]
I'm having a look

**Comment by albop** [comment]
@jan-janssen : took me a while but for the record here was that recent versions of poetry have changed the structure of the pyproject.toml file .  Since recent versions are out of conda-forge for reasons that seem above my paygrade I made a simple patch to have the receipe patch the pyproject.toml file to make it compatible with older version of poetry.

**Pull request closed without merging**
