### PR TITLE
VER: 2.0.0

### PR DESCRIPTION
**Pull request by albop**

### CODE REVIEW

**Comment by albop** [comment]
@conda-forge/core (not sure who to contact). I'm trying to fix this recipe and don't understand the linter message. On my laptop `conda-smithy recipe-lint` tells me everything is all right. Any idea?

**Comment by synapticarbors** [comment]
This is a known bug and is safe to ignore:

https://github.com/conda-forge/conda-smithy/issues/876

**Comment by synapticarbors** [comment]
@conda-forge-admin, please lint

**Comment by albop** [comment]
Thank you @synapticarbors !

**Comment by CJ-Wright** [comment]
Please use a fork https://conda-forge.org/docs/conda-forge_gotchas.html#using-a-fork-vs-a-branch-when-updating-a-recipe

**Pull request merged**
